services:
  api:
    build: .
    ports:
      - "80:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bibledb
    command: ["fastapi", "run", "main.py", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - .:/code
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
      
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bibledb
    ports:
      - "5432:5432"

volumes:
  postgres_data: 