[project]
name = "bible-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "openai>=1.76.0",
    "psycopg2-binary>=2.9.9",
    "scalar-fastapi>=1.0.3",
    "sqlmodel>=0.0.24",
]
